apiVersion: v1
kind: Pod
metadata:
  name: teste-pod
  labels:
    app.kubernetes.io/name: teste-pod
spec:
  containers:
    - name: myapp
      image: nginx:latest
      resources:
        requests:
          memory: "500Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      ports:
        - containerPort: 80
