{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: web
      port: {{ .Values.gateway.port }}
      protocol: HTTP
      hostname: {{ .Values.gateway.hostname | quote }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.gateway.allowedRoutes.namespaces.from }}
{{- end }}
