replicaCount: 5

image:
  repository: ghcr.io/kbrum/lab
  tag: "0.1.1"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

gatewayClass:
  enabled: false
  name: traefik
  controllerName: traefik.io/gateway-controller

gateway:
  enabled: true
  className: traefik
  name: lab-gateway
  hostname: "*.lab.local"
  port: 8000
  allowedRoutes:
    namespaces:
      from: All

httpRoutes:
  enabled: true
  routes:
    - name: api-route
      namespace: default
      hostname: api.lab.local
      path: /
      parent:
        name: lab-gateway
        namespace: default
      backend:
        name: lab
        port: 80

    - name: argo-ui-route
      namespace: argocd
      hostname: argo.lab.local
      path: /
      parent:
        name: lab-gateway
        namespace: default
      backend:
        name: argocd-server
        port: 80
